In [1]:
import numpy as np

In [2]:
# 1. 將下兩列 array 存成 npz 檔

In [3]:
array1 = np.array(range(30))

In [4]:
array2 = np.array([2, 3, 5])

In [5]:
with open('array.npz', 'wb') as f:
    np.savez(f, A1 = array1, A2 = array2)

In [6]:
file = np.load('array.npz')

In [7]:
print(file['A1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [8]:
print(file['A2'])

[2 3 5]


In [9]:
# 2. 讀取剛剛的 npz 檔，加入下列 array 一起存成新的 npz 檔

In [10]:
array3 = np.array([[4,5,6], [1,2,3]])

In [11]:
with open('new_array.npz', 'wb') as f:
    old = np.load('array.npz')
    np.savez(f, A1 = old['A1'], A2 = old['A2'], A3 = array3)

In [12]:
Nfile = np.load('new_array.npz')

In [13]:
Nfile.files

['A1', 'A2', 'A3']

In [14]:
print(Nfile['A1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [15]:
print(Nfile['A2'])

[2 3 5]


In [17]:
print(Nfile['A3'])

[[4 5 6]
 [1 2 3]]
